language: php
php:
  - '7.1'
  - '7.2'
  - nightly

install:
  - sudo pecl install yaml
  - travis_retry composer update --no-interaction --no-suggest
  - cd tests; git clone git@github.com:netzbegruenung/green-directory.git