language: php
php:
  - '7.2'
  - nightly

before_script:
  - sudo pecl install yaml

install:
  - travis_retry composer update --no-interaction --no-suggest
  - cd tests; git clone git@github.com:netzbegruenung/green-directory.git
