<?php

define('NETZBEGRUENUNG_GREEN_DIRECTORY_MODELS_SERIALIZER_PREFIX', 'Netzbegruenung\GreenDirectory\Model');
define('NETZBEGRUENUNG_GREEN_DIRECTORY_MODELS_SERIALIZER_METADATA', __DIR__ . DIRECTORY_SEPARATOR . 'serializer');

